name: The BukkitGames
main: me.ftbastler.BukkitGames.BGMain
version: 1.1.0
website: http://dev.bukkit.org/server-mods/bukkitgames
dev-url: http://dev.bukkit.org/server-mods/bukkitgames
author: ftbastler
startup: startup
depend: [Vault]

description: >
             The BukkitGames.
commands:
  help:
    description: Help.
    usage: /<command>
  kit:
    description: Kits.
    usage: /<command>
  kitinfo:
    description: Kits info.
    usage: /<command> [kitName]
  start:
    description: Start.
    usage: /<command>
  chest:
    description: Spawn chest.
    usage: /<command>
  rchest:
    description: Spawn chest.
    usage: /<command>
  gamemaker:
    description: GameMaker.
    usage: /<command>
  spawn:
    description: Spawn.
    usage: /<command>
  coin:
    description: Coin Menu.
    usage: /<command>
  fbattle:
    description: Final battle.
    usage: /<command>
  bgcheckversion:
    description: Checks if there is an update.
    usage: /<command>
  bgversion:
    description: Displays the current version of the plugin.
    usage: /<command>
  bgdownload:
    description: Download the new update if available.
    usage: /<command>